### ISSUE TITLE
Telegram ID is not working

### ISSUE THREAD

**Issue by 2raj2raj** [tulihub/PT-MoonBot#1]
MoonBot doesn't like my Telegram ID. The ID is good. I have tested. @TE_MoonBot

Screenshots attached.

![photo_2018-02-14_11-08-44](https://user-images.githubusercontent.com/24386973/36181108-71b54580-1177-11e8-9cec-2e0ce49f6475.jpg)

![photo_2018-02-14_10-57-28](https://user-images.githubusercontent.com/24386973/36181117-7e42a5ae-1177-11e8-934c-d0e1f1eea361.jpg)

![capture](https://user-images.githubusercontent.com/24386973/36181146-a1c7879c-1177-11e8-9ec8-3d1f1ba6cf30.JPG)

**Comment by tulihub** [comment]
As discussed on telegram, you should use @MyTelegramID_bot to get your telegram id.
