### ISSUE TITLE
Error Starting Moon Bot in Linux

### ISSUE THREAD

**Issue by jwk27** [tulihub/PT-MoonBot#10]
Using pm2 to start the app. It gave me the following error

(node:17482) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 124): Error: 400: Bad Request: chat not found

(node:17482 ) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tulihub** [comment]
@jwk27 there are two options to this error
- You didnt 'start' your telegram bot
- You entered wrong value in `bot.user_id`. Make sure you paste the same value you get from https://t.me/MyTelegramID_bot. 

For troubleshooting, join discord: https://discord.gg/aJ3Ryu7 and contact me.
