### ISSUE TITLE
ETH Balance Missing

### ISSUE THREAD

**Issue by Cryptonic2** [tulihub/PT-MoonBot#13]
Hello (I am using ETH market)

When using the “Binance” and “Summary” views, the bot is saying that the trading balance being used of the total is 100% yet there is still 0.5 ETH left which would mean the percentage should be somewhere less than 100%. This was working fine yesterday and would say it is only trading 46% of the balance or some other percentage less than 100.

Any ideas why this may be happening?

**Comment by Cryptonic2** [comment]
Just checking back in to let you know the bot eventually fixed itself. Not sure what would have caused the issue though since I didn’t see any errors.

**Comment by tulihub** [comment]
Thanks for reporting back. 
Sometimes there are network issues with binance\bittrex apis, most cases resolved by themselves.
