### ISSUE TITLE
path

### ISSUE THREAD

**Issue by keithofaptos** [tulihub/PT-MoonBot#14]
im having a problem figuring out what to fill in here:   profit.trailer.directory.path = 
i think it should be.....    /Users/mac/Applications/ProfitTrailer_Binance
because i think that's the path. but when i view full path it says:
Untitled 1/Applications/ProfitTrailer_Binance
i've tried everything i can think of. moonbot folder is out of macos folder
and is in applications as is pt_binance folder,assuming that's "near".
im pretty frustrated at this point and need/want support,asap.
thx

**Comment by tulihub** [comment]
Hi @keithofaptos, we talked in private, thats not an issue. 
thanks.
