### ISSUE TITLE
Buy Order Notifications - No Messages

### ISSUE THREAD

**Issue by Cryptonic2** [tulihub/PT-MoonBot#15]
Hello,

For some reason when profit trailer purchases coins now, Moonbot will not send buy orders to Telegram. Sales and DCA buys still are being sent. Any idea as to what may be causing the issue? I did not have any problems until today with messages being sent.

**Comment by tulihub** [comment]
Hi @Cryptonic2 
Can you please elaborate more, which OS, are you using Feeder\Magic\other add-on, etc.

**Comment by Cryptonic2** [comment]
![91fb1f9a-67f6-4f51-bf82-95b71ecc1562](https://user-images.githubusercontent.com/36640107/37173026-1c2fcf5a-22d8-11e8-8d5e-c3cdc0a5dfb6.jpeg)

**Comment by Cryptonic2** [comment]
The original buy of ICX at 11:50 AM should also get a notification from MoonBot. Instead, only the PT telegram notification was sent. Like I said before, sells of coins and and DCA buys are sent by MoonBot, but until recently it stopped sending initial purchases of coins. I am using Windows, PT and PT Magic. All 3 have been running in unison that last 3 days or so without any issue.

**Comment by avoosh** [comment]
@Cryptonic2 are you using the same telegram bot token for PT and MoonBot?

**Comment by Cryptonic2** [comment]
No, they are two separate bot tokens

**Comment by tulihub** [comment]
@Cryptonic2 did it happened on all coins or for specific pairs only?

I've released a [5.0.1](https://github.com/tulihub/PT-MoonBot/releases/tag/5.0.1) version with attempt to fix this issue. Please lmk if it solves the issue. thanks.

**Comment by Cryptonic2** [comment]
Hey Tulihub, low BNB value works great. Thanks for adding. I’m bagged up right now, but once it clears up I will let you know if New buys are working again

**Comment by Cryptonic2** [comment]
![1cf91245-e216-4213-b9cf-09ca17b401d2](https://user-images.githubusercontent.com/36640107/37360816-460df226-26bf-11e8-9bab-430fd08a46e1.jpeg)

**Comment by Cryptonic2** [comment]
@tulihub It looks like unfortunately the buy notification fix still did not work. The STORM purchase was only captured by PT itself.

**Comment by tulihub** [comment]
@Cryptonic2 Sorry about that. 
I've reverted the changes to the previous state and updated [5.0.1](https://github.com/tulihub/PT-MoonBot/releases/tag/5.0.1). I'll need more information to solve the original issue. 
You can add `moonbot.debug = true`, once you face the same issue, please provide me the logs via discord PM: https://discord.gg/aJ3Ryu7 

(you can ignore all log lines as long as your bot functions ok)

**Comment by tulihub** [comment]
@Cryptonic2 did you encounter this issue since then?

**Comment by Cryptonic2** [comment]
I’m still not seeing buys on two different instances, however, I am using the PT bot for it so it’s something I have been able to use as a workaround.

**Comment by avoosh** [comment]
@Cryptonic2 I cant reproduce this issue, if you still facing this issue, can you please send me your logs output via PM in Discord. So I will take a look.

**Comment by tulihub** [comment]
notification engine was rebuilt. 6.0.1 will have it.
