### ISSUE TITLE
[Feature Request] Support PT running against ETH pairs

### ISSUE THREAD

**Issue by 2raj2raj** [tulihub/PT-MoonBot#2]
Please support PT trading ETH pairs

**Comment by zwarbo** [comment]
I also would be interested in this feature. Thanks

**Comment by CryptoSpidey** [comment]
Same, it would be wonderful, same reason I did not subscribed for paid version!

**Comment by snortch** [comment]
Will happily pay for this when ETH pairs are supported!

**Comment by JamjamMcjammerson** [comment]
I’m on eth market and would buy if moonbot I’d this happened.

**Comment by tulihub** [comment]
first beta version of ETH support should come in the next release.

**Comment by tulihub** [comment]
https://github.com/tulihub/PT-MoonBot/releases/tag/5.0.0
^ with BETA support in ETH. 

Please file new issues as needed. 
Thank you !
