### ISSUE TITLE
Error Message - Paid MoonBot

### ISSUE THREAD

**Issue by Binildos** [tulihub/PT-MoonBot#6]
Hi,

I was using MoonBot and it was working smoothly. So, I bought the license, since I liked to have the remote control over my Bot, and MoonBot was still functioning perfectly. However, when I turned off my PT Bot and restated it, alongside with MoonBot, the following message took place:

Error in ProfitTrailer!
2018-02-20 21:52:55 ERROR BinanceWebSocketAdapter24Ticker - Error in websocket message ERROR: -1003, Too many requests; current limit is 1200 requests per minute. Please use the websocket for live updates to avoid polling the API.

Please Help!

Thanks in advance.

**Comment by tulihub** [comment]
Hi 
This is not moonbot issue, but its a PT issue.
As you see, Moonbot just notified you he found an Error in PT logs (thats part of moonbot work).

You can easily check PT github for more info. https://github.com/taniman/profit-trailer
