### ISSUE TITLE
Incorrect time in messages

### ISSUE THREAD

**Issue by smoochy** [tulihub/PT-MoonBot#8]
Hi,

I am located in UTC +1 and have `set server.timeZoneOffset = +01:00` in my PT applications.properties.

As far as I am aware, there is not a similar option for moonbot.

Just recently, on 25.02.2017 at 0.57am I did a sell. But the time in the Telegram message was "Date: 24.02.2018 | Time 23:57" which translates into UTC +0.

Is there any ways to adjust that?

**Comment by tulihub** [comment]
Yes, timezone offset property will be added

**Comment by tulihub** [comment]
https://github.com/tulihub/PT-MoonBot/releases/tag/5.0.0
^ Added property to version 5.0.0, i.e. `moonbot.timezone.offset = +1`

Thank you!
