### ISSUE TITLE
Moonbot permanently changing PT config files

### ISSUE THREAD

**Issue by smoochy** [tulihub/PT-MoonBot#9]
For some reason, Moonbot is permanently - every 15s - accessing and changing setting files of Profit Trailer. I don't knowh which, but it is being shown in PT log. As soon as I stop moonbot.exe (see picture below 2:12:56), PT log isn't spammed anymore.

Windows Server 2016. PT 1.2.6.19

![moonbot](https://user-images.githubusercontent.com/34371932/36636991-31b8ef5a-19d2-11e8-91a8-5517f21a3bd6.jpg)

**Comment by 2raj2raj** [comment]
This not moonbot. It’s your setup. Open all the properties files and save them to update their file date stamp to fix this.

**Comment by smoochy** [comment]
You should not jump to rapidly to conclusions.

> **As soon as I stop moonbot.exe (see picture below 2:12:56), PT log isn't spammed anymore.**


Updating Moonbot to 4.1.3 solved the issue

**Comment by tulihub** [comment]
Solved in 4.1.3
